#!/bin/sh
# /etc/hotplug.d/iface/26-grey
if [ "$ACTION" = "ifup" -a "$INTERFACE" = "wan" ]; then     #проверяем событие и название интерфейса

. /lib/functions/network.sh; network_get_ipaddr ip wan     #получаем адрес интерфейса, адрес передается в переменную ip
_ip=$(echo $ip | grep -v -E "(^100\.6[4-9]\.|^100\.[7-9][0-9]\.|^100\.1[0-1][0-9]\.|^100\.12[0-7]\.)") #проверяем адрес на принадлежность диапазону 100.64.0.0/10
[ -z "$_ip" ]  && logger -t grey_ip "Reloading wan due grey IP - $ip" && ifup wan #переподключаем интерфейс wan, пишем в syslog
fi
